---
- project:
    name: openstack-k8s-operators/lightspeed-operator
    default-branch: main
    github-check:
      jobs:
        - openstack-k8s-operators-content-provider
        - lightspeed-operator-kuttl

- job:
    name: lightspeed-operator-kuttl
    parent: cifmw-base-multinode-kuttl
    dependencies:
      - openstack-k8s-operators-content-provider
    attempts: 1
    irrelevant-files: &irrelevant-files
      - ^.*/*\.md$
      - ^\..*$
      - ^docs/.*$
      - ^LICENSE$
      - ^OWNERS$
      - ^OWNERS_ALIASES$
      - ^PROJECT$
      - ^README.md$
      - tests?\/functional
      - roles/.*/molecule/.*
    pre-run: playbooks/kuttl/pre-run.yaml
    vars:
      cifmw_kuttl_tests_operator_list:
        - openstack_lightspeed
