apiVersion: lightspeed.openstack.org/v1beta1
kind: OpenStackAssistant
metadata:
  labels:
    app.kubernetes.io/name: openstack-lightspeed-operator
    app.kubernetes.io/managed-by: kustomize
  name: assistant
spec:
  containerImage: quay.io/dprince/goose:oc-fedora
  provider: goose
  lightspeedStack:
    providerSecret: lightspeed-provider-config
    caBundleSecretName: lightspeed-ca-bundle
  goose:
    recipes: assistant-recipes
    hints: assistant-hints
    mcpServers:
      - name: openstack
        openstackClientRef: openstackclient
  env:
    - name: GOOSE_MODEL
      value: "gemini/models/gemini-2.5-flash"
    - name: LIGHTSPEED_API_KEY
      value: "dummy"
