---
- name: "Deploy OpenStack Lightspeed Operator"
  hosts: "{{ cifmw_zuul_target_host | default('all') }}"
  gather_facts: true
  tasks:
    - name: Filter out host if needed
      when:
        - cifmw_zuul_target_host is defined
        - cifmw_zuul_target_host != 'all'
        - inventory_hostname != cifmw_zuul_target_host
      ansible.builtin.meta: end_host

    # Make cifmw general plugins available when nested Ansible executed
    - name: Make a symlink to local .ansible collection dir
      ansible.builtin.include_role:
        name: cifmw_helpers
        tasks_from: symlink_cifmw_collection.yml

    - name: Run pre_test hooks
      vars:
        step: pre_test
      ansible.builtin.import_role:
        name: run_hook
