name: "Verify generated files"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  verify-generation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

    - name: Set up Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
      with:
        go-version-file: "go.mod"

    - name: Install operator-sdk
      uses: redhat-actions/openshift-tools-installer@37eb3cfb20ac2df6f0511ffa71cd917e4d49cabf # v3
      with:
        source: github
        operator-sdk: 1.38.0

    - name: Verify generated files are up to date and fail if anything changed
      run: |
        make generate
        make manifests

        git diff --exit-code
